### PR TITLE
Objects can have a 'topic' property

### PR DESCRIPTION
**Pull request by galfert**
When sending a topic change update message (in IRC), I got an exception in Sockethub saying

```
Error: invalid property topic
```

This change allows the `topic` property.

### CODE REVIEW

**Comment by galfert** [comment]
Also found a wrong rename value for the `platform` property (`@context` was missing the "@").

And I updated the browserify builds. So the tests are all green again now :)

**Comment by silverbucket** [comment]
@galfert this looks good, thanks! but the `@context` is actually different than `context`, the platform actually is supposed to be `context`

**Comment by galfert** [comment]
Ok, that's weird. I'm pretty sure there was a failing test without the change for the `context`.

**Comment by silverbucket** [comment]
Could be an error in the test? I did initially make the error of misnaming
some `context`'s as `@context` so I might have missed some when I fixed it.

**Comment by galfert** [comment]
Ok, if you are really sure I can revert my change and adapt the tests instead.

E.g. one of the failing tests was this one: https://github.com/galfert/activity-streams.js/blob/add-topic-property/test/basics-suite.js#L84

**Comment by silverbucket** [comment]
@galfert yeah I'm definitely sure that `platform` is now `context`. `@context` is used to define the ontology (ie. as2.0 URI)

**Comment by galfert** [comment]
Ok, I reverted my change for `context` and fixed the tests instead.

@silverbucket I think this should be all good to go now.

**Comment by silverbucket** [comment]
awesome, thanks @galfert !

**Pull request merged**
